language: java
sudo: false
install: true
addons:
  sonarqube:
    token:
      secure: SONAR_TOKEN
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install: echo "MAVEN_OPTS='-Xmx512m -XX:MaxPermSize=512m'" > ~/.mavenrc
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'