language: java
sudo: false
install: true
addons:
  sonarqube:
    token:
      secure: SONAR_TOKEN
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
      - graphviz
script:
  - if [ $TRAVIS_PULL_REQUEST == "false" ]; then
      mvn clean -e org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN;
    else
      mvn clean -e org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.github.oauth=$GITHUB_TOKEN -Dsonar.github.pullRequest=$TRAVIS_PULL_REQUEST -Dsonar.github.repository=$TRAVIS_REPO_SLUG -Dsonar.analysis.mode=preview;
    fi
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: target
  github_token:  $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
